{
 "title": "Demo Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Time Interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "quantile", "label": "Quantile", "query": "0.25,0.5,0.75,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Gauge Seasonal Value Demo",
   "type": "graph",
   "description": "A gauge is simply an integer value that can go up or down. It is reported directly and can be used without query functions like rate(). Here it displays a series with some recurring (seasonal) features.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "demo_gauge_value",
     "legendFormat": "Seasonal metric exposed by the {{application}}"
    }
   ]
  },
  {
   "title": "Gauge Queue Size Demo",
   "type": "graph",
   "description": "A gauge is simply an integer value that can go up or down. It is reported directly and can be used without query functions like rate(). Here it displays the size of a queue which decreases and resets at some point.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "demo_gauge_size", "legendFormat": "Number of objects in a queue" }
   ]
  },
  {
   "title": "Counter Demo",
   "type": "graph",
   "description": "Since these counters increase by the same amount in a regular interval, using rate() shows two constant line graphs.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(demo_counter_total[$interval])",
     "legendFormat": "Rate of increase for counter in \"{{method}}\""
    }
   ]
  },
  {
   "title": "DistributionSummary Demo",
   "type": "graph",
   "description": "This graph shows the sum of values reported by the seasonal gauge. Using the drop-down menu on the top left side we can control the time interval over which this sum is calculated. Selecting a large value like 30m reveals an upward trend in the series. ",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(demo_summary_fahrenheit_sum[$interval])",
     "legendFormat": "Average of the values over a $interval interval"
    }
   ]
  },
  {
   "title": "Timer Demo (dynamic)",
   "type": "graph",
   "description": "This timer could represent the duration of an event within the application. The percentiles of this timer are can be dynamically calculated in Grafana, since the individual counts for each bucket are available.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(demo_timer_seconds_bucket[1m])) by (le))",
     "legendFormat": "${quantile}th percentile of measured time values"
    }
   ]
  },
  {
   "title": "Timer Demo (hardcoded)",
   "type": "graph",
   "description": "This timer could represent the duration of an event within the application. The percentile calculation of this timer is done client-side and can't be dynamically adjusted in Grafana.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "demo_timer_seconds{percentileType=\"hardcoded\"}",
     "legendFormat": "{{quantile}}th percentile of measured time values"
    }
   ]
  }
 ]
}